### ISSUE TITLE
Compatibility with apollo client 2

### ISSUE THREAD

**Issue by crubier** [alexandrebodin/storybook-addon-apollo-graphql#1]

**Comment by alexandrebodin** [comment]
Hi @crubier,

I'm not currently maintaining the addon. If many people want I will though. 

In any case PRs are welcome if you'd like to help ;)

**Comment by alexandrebodin** [comment]
@crubier 

Starting from `v2.0.0` you can use this lib with apollo-client 2

If you can try it out and give me your feedbacks ;)

Thanks a lot
