### ISSUE TITLE
Need ability to pass in `resolverValidationOptions` to `makeExecutableSchema`

### ISSUE THREAD

**Issue by ruswerner** [alexandrebodin/storybook-addon-apollo-graphql#2]
I am getting warnings due to not having certain `resolveType()` functions declared. They aren't really required when using mocks, but the only way to disable these warnings is to pass:

    resolverValidationOptions :{
      requireResolversForResolveType: false
    },

to `makeExecutableSchema`.

The warnings look like this:

    Type "Linkable" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.

**Comment by alexandrebodin** [comment]
Hi @ruswerner,

Thank you for the feedback, I think we can had an options object to pass to makeExecutableSchema to give more control over it.

I'll work on it next week, A PR is of course welcome if you want to give it a try ;)

Cheers

**Comment by ruswerner** [comment]
Thanks @alexandrebodin ! I'll see if I can create a PR, but next week is not too long to wait for us :)

**Comment by alexandrebodin** [comment]
@ruswerner I just released v2.1.0 with two extra args : `schemaOptions` and `mockOptions`that will respectively pass the options to `makeExecutableSchema` and `addMockFunctionToSchema`

Hope this helps ;)

**Comment by ruswerner** [comment]
@alexandrebodin Awesome thanks! I'll give it a try today and let you know. Cheers.

**Comment by ruswerner** [comment]
@alexandrebodin Just pulled 2.1.0 and updated my stories; all working just as expected. Many thanks!
